/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalForms;

import readWrite.DataSource;
import readWrite.SignedIn;
import Interface.FileInterface;
import entities.Faculty;

import entities.Institution;
import java.awt.Container;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class RegisterUniversity extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegisterUniversity
     */
    public RegisterUniversity() {
        initComponents();
        // remove northPane
        Container pane = ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        pane.remove(0);
        pane.getComponent(0).setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InsID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        instName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        FacultyList = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        FID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        getFaculty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 247, 247));
        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Register Institution");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Institution ID");

        InsID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        InsID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));
        InsID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Institution Name");

        instName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));
        instName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instNameActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(FacultyList);

        jButton2.setBackground(new java.awt.Color(227, 233, 237));
        jButton2.setText("Register University");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 244, 244)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        FID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Faculty ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Faculty Name");

        getFaculty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getFaculty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
        jLabel8.setText("Add More");
        jLabel8.setToolTipText("Click to add more Faculties");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel4.setText("Add atleast one faculty to University specified above.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsID, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(96, 96, 96))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FID, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(getFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsIDActionPerformed

    private void instNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instNameActionPerformed
    DefaultListModel listModel = new DefaultListModel();
    HashMap<String, String> hashMap = new HashMap<>();

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String message = "";
        if (instName.getText().equals("") || InsID.getText().equals("") || FacultyList.getModel().getSize() == 0) {
            message = "Please fill out all fields";
        } else {

            //add institution
            Institution institution = new Institution();

            institution.setInstitutionName(instName.getText());

            institution.setInstitutionID(InsID.getText().toLowerCase());

            institution.setAdmin(SignedIn.getAdmin().getEmail().toLowerCase());

            ArrayList<String> fid = new ArrayList();

            for (Map.Entry<String, String> key : hashMap.entrySet()) {
                fid.add(key.getKey().toLowerCase());
            }

            institution.setFacultyID(fid);

            //register university
            HashMap<String, Institution> universityMap;
            //retrive object
            boolean flag = false;
            boolean success = false;

            if (new DataSource().readObject(FileInterface.INSTITUTIONS_FILE) != null) {
                universityMap = (HashMap<String, Institution>) new DataSource().readObject(FileInterface.INSTITUTIONS_FILE);
                //check if university aleady exits
                for (Map.Entry<String, Institution> key : universityMap.entrySet()) {
                    if (key.getKey().toLowerCase().equals(institution.getInstitutionID())) {
                        flag = true;
                    }
                }
                if (flag) {
                    message = "Unversity already exits";
                } else {
                    universityMap.put(InsID.getText().toLowerCase(), institution);
                    if (addUniversity(universityMap)) {
                        success = true;
                    }
                }
            } else {
                universityMap = new HashMap();
                universityMap.put(InsID.getText().toLowerCase(), institution);
                if (addUniversity(universityMap)) {
                    success = true;
                }
            }
            if (success) {
                boolean sc = false;
                //add fuculty
                if (hashMap.size() > 0) {
                    for (Map.Entry<String, String> mp : hashMap.entrySet()) {
                        if (new Faculty().addFaculty(mp.getKey(), mp.getValue())) {
                            sc = true;
                        }
                    }
                }
                if (sc) {
                    message = "University added";
                    getRootPane().getParent().setVisible(false);
                }
            }
            JOptionPane.showMessageDialog(this, message);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        FacultyList.setModel(listModel);
        if (!"".equals(FID.getText()) && !"".equals(getFaculty.getText())) {
            listModel.addElement(FID.getText() + "- " + getFaculty.getText());
            //populate arrayList
            hashMap.put(FID.getText(), getFaculty.getText());
            FID.setText("");
            getFaculty.setText("");
        }
    }//GEN-LAST:event_jLabel8MouseClicked
    public boolean addUniversity(HashMap<String, Institution> universityMap) {
        //write to stream
        if (new DataSource().writeObject(universityMap, FileInterface.INSTITUTIONS_FILE)) {
            //insert faculties list
            Faculty faculty = new Faculty();
            hashMap.entrySet().stream().filter((key) -> (faculty.addFaculty(key.getKey(), key.getValue())));
            return true;
        }
        return false;
    }

    public boolean updateUniversity(Institution institution) {
        HashMap<String, Institution> map = null;
        if (new DataSource().readObject(FileInterface.INSTITUTIONS_FILE) != null) {
            //retrive and remove
            map = (HashMap<String, Institution>) new DataSource().readObject(FileInterface.INSTITUTIONS_FILE);

            System.out.println(map.remove(institution.getInstitutionID().toLowerCase()));
            map.put(institution.getInstitutionID(), institution);
            //update file
            return new DataSource().writeObject(map, FileInterface.INSTITUTIONS_FILE);

        }
        return false;
    }

    public Institution getInstitution(String key) {
        HashMap<String, Institution> hashMap = null;
        if (new DataSource().readObject(FileInterface.INSTITUTIONS_FILE) != null) {
            hashMap = (HashMap<String, Institution>) new DataSource().readObject(FileInterface.INSTITUTIONS_FILE);
            for (Map.Entry<String, Institution> map : hashMap.entrySet()) {
                if (map.getKey().toLowerCase().equals(key)) {
                    return hashMap.get(key);
                }
            }
        }
        return null;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FID;
    private javax.swing.JList<String> FacultyList;
    private javax.swing.JTextField InsID;
    private javax.swing.JTextField getFaculty;
    private javax.swing.JTextField instName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
