/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalForms;

import readWrite.DataSource;
import readWrite.SignedIn;
import Interface.FileInterface;
import entities.Faculty;
import entities.Institution;
import entities.Programme;
import java.awt.Container;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class RegisterFaculty extends javax.swing.JInternalFrame {

    private ArrayList<Programme> progList = new ArrayList();
    private Programme p = new Programme();
    private String key;

    /**
     * Creates new form RegisterFaculty
     */
    public RegisterFaculty() {
        initComponents();
        // remove northPane
        Container pane = ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        pane.remove(0);
        pane.getComponent(0).setVisible(false);
        loadData();
        listSelected();
    }

    private void listSelected() {
        univerityList.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    setKey("");
                    String a = univerityList.getSelectedItem().toString();
                    //search list
                    HashMap<String, Institution> hashMap = null;
                    try {
                        if (new DataSource().readObject(FileInterface.INSTITUTIONS_FILE) != null) {
                            hashMap = (HashMap<String, Institution>) new DataSource().readObject(FileInterface.INSTITUTIONS_FILE);
                            for (Map.Entry<String, Institution> key : hashMap.entrySet()) {
                                if (key.getValue().getInstitutionName().toLowerCase().equals(a.toLowerCase())) {
                                    //populate list of faculty
                                    if (key.getKey() != null) {
                                        setKey(key.getKey());
                                    }
                                }
                            }
                        }
                    } catch (Exception ex) {
                        //log error
                    }
                }
            }
        }
        );
    }

    private void loadData() {

        HashMap<String, Institution> institution = null;
        DefaultComboBoxModel<String> boxModel = new DefaultComboBoxModel<>();
        boxModel.addElement("Select University");
        try {
            if (new DataSource().readObject(FileInterface.INSTITUTIONS_FILE) != null) {
                //populate fields
                institution = (HashMap<String, Institution>) new DataSource().readObject(FileInterface.INSTITUTIONS_FILE);

                univerityList.setModel(boxModel);

                for (Map.Entry<String, Institution> key : institution.entrySet()) {
                    if (key.getValue().getAdmin().equals(SignedIn.getAdmin().getEmail())) {
                        boxModel.addElement(key.getValue().getInstitutionName());
                    }
                }

            }
        } catch (Exception ex) {
            //log error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        univerityList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        facultyID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        facultyName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        programID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        programName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPrograms = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Select University");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Faculty ID");

        facultyID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Faculty Name");

        facultyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));

        jButton2.setBackground(new java.awt.Color(255, 193, 7));
        jButton2.setText("Add Faculty");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        programID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));
        programID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programIDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Program ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Program Name");

        programName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));
        programName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Programmes Added will display here");

        listPrograms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 250)));
        listPrograms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listPrograms);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(univerityList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(37, 37, 37)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(facultyName)
                                .addComponent(facultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(programID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(69, 69, 69)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(programName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(univerityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(facultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (getKey() == null || getKey().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please select university");

        } else {
            //retrive university
            RegisterUniversity ru = new RegisterUniversity();
            Institution institution = ru.getInstitution(getKey());
            if (facultyID.getText().equals("") || facultyName.getText().equals("") || listPrograms.getModel().getSize() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please fill out all fields, Add atleast one programme");
            } else {

                //write to file
                Faculty f = new Faculty();
                institution.getFacultyID().add(facultyID.getText().toLowerCase());
                boolean success = false;
                //update university file
                if (ru.updateUniversity(institution)) {
                    //add faculty to faculty file
                    if (f.addFaculty(facultyID.getText().toLowerCase(), facultyName.getText())) {
                        //add PROGRAMMES
                        Programme addProgram = new Programme();
                        System.out.println(progList);
                        Iterator itr = progList.listIterator();
                        //add faculty od for each program

                        while (itr.hasNext()) {
                            Programme pList = (Programme) itr.next();
                            pList.setFacultyID(facultyID.getText().toLowerCase());

                            if (addProgram.addPrograme(pList.getProgID(), pList.getProgName(), pList.getFacultyID().toLowerCase())) {
                                getRootPane().getParent().setVisible(false);
                            }
                            success = true;
                        }
                        if (success) {
                            JOptionPane.showMessageDialog(rootPane, "Faculty and programmes added");
                        }
                    }
                }

            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed
    DefaultListModel listModel = new DefaultListModel();
    private void programIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programIDActionPerformed

    private void programNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programNameActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        if (!"".equals(programID.getText()) && !"".equals(programName.getText())) {
            listModel.addElement(programID.getText() + " - " + programName.getText());
            listPrograms.setModel(listModel);
            p = new Programme();
            p.setProgID(programID.getText());
            p.setProgName(programName.getText());
            progList.add(p);

            programID.setText("");
            programName.setText("");
        }
    }//GEN-LAST:event_jLabel7MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField facultyID;
    private javax.swing.JTextField facultyName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listPrograms;
    private javax.swing.JTextField programID;
    private javax.swing.JTextField programName;
    private javax.swing.JComboBox<String> univerityList;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the key
     */
    public String getKey() {
        return key;
    }

    /**
     * @param key the key to set
     */
    public void setKey(String key) {
        this.key = key;
    }
}
